### ISSUE TITLE
Another updater

### ISSUE THREAD

**Issue by imsoftware** [CodeBrauer/Wordpress-Git-Private-Plugin-Updater#1]
Schau mal hier: 
https://github.com/imsoftware/wp-imap-auth/blob/master/wp-updater/updater.php

Der Update müsste in etwa deine Anforderungen erfüllen.

**Comment by CodeBrauer** [comment]
Danke, hatte bereits diesen Artikel gesehen, scheint fast gleich zu sein. Danke!

https://www.smashingmagazine.com/2015/08/deploy-wordpress-plugins-with-github-using-transients
